--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KingDbrm/TheEnderchest
build-by-default: true
branches:
 - main
projects:
  TheEnderchest:
    path: ""
    requires:
    - name: KingDbrm/TheLibrary
      version: "^1.0"
...
