--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KingDbrm/TheEnderchest
build-by-default: true
branches:
  master:
    target: "src"
    php:
      - "7.4"
      - "8.1"
    path: ""
projects:
  TheEnderchest:
    path: ""
    name: TheEnderchest
...
