name: TheEnderchest
main: the\enderchest\Loader
api: 5.0.0
version: 2.0.0

load: POSTWORLD
depend: TheLibrary

autoload:
  muqsit: libs/muqsit/
  block: libs/block/
  item: libs/item/
  rajadordev: libs/rajadordev/

permissions:
  enderchest.command:
    default: op
  36.slots.use:
    default: op
  45.slots.use:
    default: op
  54.slots.use:
    default: op
