# Use {player} for the player name
# Permission of 27 slots: "27.slots.use"
# Permission of 36 slots: "36.slots.use"
# Permission of 27 slots: "27.slots.use"
enderchest-name: "Enderchest de @{player}"